name: Semgrep Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:  # 👈 Enables manual trigger from GitHub UI

jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep and Upload to Semgrep Cloud
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
