name: Semgrep Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep and Upload to Semgrep Cloud
        uses: returntocorp/semgrep-action@v1.10.0  # ✅ Use a modern version
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
